esphome:
  name: water_flow
  platform: ESP8266
  board: nodemcuv2
  includes:
    - water_flow/src/water_flow.h

wifi:
  ssid: "XXXX"
  password: "XXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XXXX"
    password: "XXXX"

captive_portal:

# Enable Home Assistant API
api:
  password: "XXXX"

ota:
  password: "XXXX"
    
# This is for saving the Total Gallons Used every ten gallons, incase of a power cycle
globals:
  - id: saved_gallons_count
    type: int
    restore_value: yes
    
sensor:
- platform: custom
  lambda: |-
    auto wf = new WaterFlowSensor();
    App.register_component(wf);
    return {wf->flow_rate_gpm_sensor, wf->gallons_used_sensor};
  sensors:
  - name: "Water Flow Rate"
    unit_of_measurement: . # using this because you have to have a unit_of_measurement to see the history graph, but the guage card doesn't look good when displaying a unit
    #unit_of_measurement: GPM
    accuracy_decimals: 2
    id: flow_rate
  - name: "Total Gallons Used"    
    unit_of_measurement: . # using this because you have to have a unit_of_measurement to see the history graph, but the guage card doesn't look good when displaying a unit
    #unit_of_measurement: Gal
    accuracy_decimals: 2
    # Every ten gallons used, we will write the value to flash so it can be restored if power is ever lost
    on_value:
      then:
        - lambda: |-
            if (!((int)x % 10) && ((int)x != id(saved_gallons_count) && ((int)x != 0))) {
              id(saved_gallons_count) = x;
            }

binary_sensor:
  - platform: template
    name: "Water Running"
    lambda: |-
      return (id(flow_rate).state > 0);
