esphome:
  name: water_flow
  platform: ESP8266
  board: nodemcuv2
  esp8266_restore_from_flash: true
  includes:
    - water_flow/src/water_flow.h
  
wifi:
  ssid: "XXXX"
  password: "XXXX"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "XXXX"
    password: "XXXX"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "XXXX"

ota:
  password: "XXXX"
  
# This is for saving the total_water_used_sensor every ten gallons/liters, incase of a power cycle
globals:
  - id: saved_usage_count
    type: int
    restore_value: yes
  - id: save_usage_frequency
    type: int    
    initial_value: 'UNITS'
    
sensor:
- platform: custom
  lambda: |-
    auto wf = new WaterFlowSensor();
    App.register_component(wf);
    return {wf->flow_rate_sensor, wf->total_water_used_sensor};
  sensors:
  - name: "Water Flow Rate"
    unit_of_measurement: GPM # Gallons or Liters per minute
    accuracy_decimals: 2
    id: flow_rate
  - name: "Total Water Used"
    unit_of_measurement: Gal
    accuracy_decimals: 2
    # Every so often, we will write the value to flash so it can be restored if power is ever lost
    on_value:
      then:
        - lambda: |-
            if (!((int)x % id(save_usage_frequency)) && ((int)x != id(saved_usage_count) && ((int)x != 0))) {
              id(saved_usage_count) = x;
            }

binary_sensor:
  - platform: template
    name: "Water Running"
    lambda: |-
      return (id(flow_rate).state > 0);
